export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const TRIGGER_MESSAGE = 'TRIGGER_MESSAGE';
export const UPDATE_USER_POSITION = 'UPDATE_USER_POSITION';
export const SET_CURRENT_CONV_USER_INFO = 'SET_CURRENT_CONV_USER_INFO';
export const UPDATE_CALLING_USER = 'UPDATE_CALLING_USER';